name: dqgs
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - sympy
  - numba
  - sparse
  - matplotlib
  - jupyterlab
  - ipykernel
  - pytest
  - typer
  - pip
  - pip:
      - jax
      - jaxlib
      - optax
